# -*- coding: utf-8 -*-
"""Project_5Module_plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12A7Wfl59YGBIsZwu14Je2IRc5LZbODEQ

Title: Exploratory Analysis with Plotting – Bike Share Data
Discription: Showing the frequency of the registered bikes, calculating their medium year-wise 2011,2012 by using plot.
Created by Vamshi Krishna Kichannapalle.
"""

import pandas as pd
import matplotlib.pyplot as plt

# 1. Read in the bike_share_data.csv file
bikesData = pd.read_csv('/content/bike_share_data python.csv')

# 2. Create histogram for registered bike users
plt.figure(figsize=(10, 6))
plt.hist(bikesData['registered'], bins=20, color='skyblue')
plt.xlabel('Number of Registered Bike Users')
plt.ylabel('Frequency')
plt.title('Distribution of Registered Bike Users')
plt.grid(True)
plt.show()

# 3. Bar plot for median registered riders by month for 2011 and 2012
bikesData['dteday'] = pd.to_datetime(bikesData['dteday'])
bikesData['year'] = bikesData['dteday'].dt.year
bikesData['month'] = bikesData['dteday'].dt.month
medianRegisteredByMonth2011 = bikesData[bikesData['year'] == 2011].groupby('month')['registered'].median()
medianRegisteredByMonth2012 = bikesData[bikesData['year'] == 2012].groupby('month')['registered'].median()

plt.figure(figsize=(12, 6))
plt.subplot(1, 2, 1)
medianRegisteredByMonth2011.plot(kind='bar', color='lightgreen')
plt.title('Median Registered Riders by Month - 2011')
plt.xlabel('Month')
plt.ylabel('Median Registered Riders')

plt.subplot(1, 2, 2)
medianRegisteredByMonth2012.plot(kind='bar', color='lightblue')
plt.title('Median Registered Riders by Month - 2012')
plt.xlabel('Month')
plt.ylabel('Median Registered Riders')

plt.tight_layout()
plt.show()

# 4. Bar plot for median registered riders by hour for July (both years)
julyData = bikesData[(bikesData['year'] == 2011) | (bikesData['year'] == 2012)]
julyData = julyData[julyData['month'] == 7]
medianRegisteredByHourJuly = julyData.groupby('dteday')['registered'].median()

plt.figure(figsize=(10, 6))
medianRegisteredByHourJuly.plot(kind='bar', color='orange')
plt.title('Median Registered Riders by Hour - July')
plt.xlabel('Hour')
plt.ylabel('Median Registered Riders')
plt.xticks(rotation=0)
plt.grid(True)
plt.show()

# 5. Bar plot for median registered riders by day
bikesData['day'] = bikesData['dteday'].dt.day_name()
medianRegisteredByDay= bikesData.groupby('day')['registered'].median()

plt.figure(figsize=(14, 6))
medianRegisteredByDay.plot(kind='bar', color='lightcoral')
plt.title('Median Registered Riders by Day')
plt.xlabel('Day')
plt.ylabel('Median Registered Riders')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

# 6. Scatter plot for windspeed vs number of registered riders for March 2011
marchData2011 = bikesData[(bikesData['year'] == 2011) & (bikesData['month'] == 3)]
plt.figure(figsize=(10, 6))
plt.scatter(marchData2011['windspeed'], marchData2011['registered'], color='purple')
plt.title('Windspeed vs Registered Riders - March 2011')
plt.xlabel('Windspeed')
plt.ylabel('Number of Registered Riders')
plt.grid(True)
plt.show()

"""Findings:
1. The histogram demonstrates a right-skewed distribution of registered bike users, meaning that while there are generally fewer registered bike riders on most days, there are occasionally days with noticeably more users.
2. The bar plots displaying the median number of registered riders by month in 2011 and 2012 demonstrate how the median number of registered riders fluctuates in different months, with certain months having greater medians than others.
3. The hourly bar plot of the July median registered riders reveals peak hours during the day when the median number of registered riders is higher, suggesting periods of possible increased demand.
4. The demand fluctuates throughout the week, with certain days having higher median registered riders than others, as seen by the bar plot for median registered riders by day.
5. There is no discernible correlation between windspeed and the number of registered riders in the March 2011 scatter plot of windspeed vs. registered riders.

Business decision: Depending on the identified peak hours and days of higher demand, one business decision based on the insights from the exploratory analysis could be to modify bike availability and marketing efforts. Increasing the quantity of bikes available or implementing focused marketing campaigns on busy days and hours, for example, may draw in more clients and boost sales.

"""